--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.9) ~  Much Love, Ferib 

]]--

local v0=game.Players.LocalPlayer.Name;local v1="https://kellzyy-hub.my.id/api/update";local v2=request or http_request or (http and http.request) or (syn and syn.request) ;if  not v2 then warn("Executor kamu tidak mendukung HTTP Request!");end print("🔥 Dashboard Logger 100% OTOMATIS Started for "   .. v0   .. " 🔥" );local function v3() local v4={};local v5={};local v6={};local v7=game.Players.LocalPlayer;local function v8(v9) if  not v9 then return;end for v13,v14 in pairs(v9:GetChildren()) do if v14:IsA("Tool") then if ((v14.Name=="Build") or (v14.Name=="Shovel")) then continue;end if  not v4[v14.Name] then v4[v14.Name]=0;end local v15=1 -0 ;local v16=v14:GetAttribute("Count");if (v16 and (typeof(v16)=="number") and (v16>(0 -0))) then v15=v16;end v4[v14.Name]=v4[v14.Name] + v15 ;if (v14.TextureId and (v14.TextureId~="")) then local v28=1065 -(68 + 997) ;local v29;while true do if (v28==(1270 -(226 + 1044))) then v29=v14.TextureId:match("%d+");if v29 then v5[v14.Name]=v29;end break;end end end local v18=v14:GetAttribute("MainCategory") or v14:GetAttribute("Category") ;if  not v18 then if ((v14.Name=="Unicorn") or (v14.Name=="Owl") or v14.Name:lower():find("pet")) then v18="Pet";end end local v19=v14.Name:lower();if v19:find("mushroom") then v18="Gear";end if ((v18=="Prop") or (v18=="Props")) then v18="Crate";end if v18 then v6[v14.Name]=tostring(v18);end end end end v8(v7:FindFirstChild("Backpack"));if v7.Character then v8(v7.Character);end return v4,v5,v6;end task.spawn(function() while true do local v10=0 -0 ;local v11;local v12;while true do if (v10==(117 -(32 + 85))) then v11,v12=pcall(function() local v20=0 + 0 ;if (game.Players.LocalPlayer:FindFirstChild("leaderstats") and game.Players.LocalPlayer.leaderstats:FindFirstChild("Sheckles")) then v20=game.Players.LocalPlayer.leaderstats.Sheckles.Value;end local v21,v22,v23=v3();local v24={bot_id=v0,shekless=v20,items=v21,textures=v22,categories=v23};local v25=game:GetService("HttpService");local v26=v25:JSONEncode(v24);if v2 then task.spawn(function() local v32=0 + 0 ;local v33;while true do if (v32==(957 -(892 + 65))) then v33=v2({Url=v1,Method="POST",Headers={["Content-Type"]="application/json",["Bypass-Tunnel-Reminder"]="true"},Body=v26});if (v33 and (v33.StatusCode==200)) then print("[Dashboard] Data Uang & Tas terkirim otomatis untuk: "   .. v0 );else warn("[Dashboard Error] Gagal mengirim! Status: "   .. tostring((v33 and v33.StatusCode) or "Unknown" ) );end break;end end end);end end);if  not v11 then warn("[Dashboard Error] "   .. tostring(v12) );end v10=2 -1 ;end if (v10==(1 -0)) then task.wait(27 -12 );break;end end end end);
